/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.is4300.appman;

/**
 *
 * @author quinc
 */
public class CreateNewForm extends javax.swing.JFrame {

    /**
     * Creates new form CreateNewForm
     */
    public CreateNewForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ToolBoxPanel = new javax.swing.JTabbedPane();
        OSTab = new javax.swing.JPanel();
        LanguageTab = new javax.swing.JPanel();
        BuildToolTab = new javax.swing.JPanel();
        WorkBenchWindow = new javax.swing.JSplitPane();
        WorkbenchPanel = new javax.swing.JPanel();
        SettingsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout OSTabLayout = new javax.swing.GroupLayout(OSTab);
        OSTab.setLayout(OSTabLayout);
        OSTabLayout.setHorizontalGroup(
            OSTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        OSTabLayout.setVerticalGroup(
            OSTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        ToolBoxPanel.addTab("Operating System", OSTab);

        javax.swing.GroupLayout LanguageTabLayout = new javax.swing.GroupLayout(LanguageTab);
        LanguageTab.setLayout(LanguageTabLayout);
        LanguageTabLayout.setHorizontalGroup(
            LanguageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        LanguageTabLayout.setVerticalGroup(
            LanguageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        ToolBoxPanel.addTab("Language", LanguageTab);

        javax.swing.GroupLayout BuildToolTabLayout = new javax.swing.GroupLayout(BuildToolTab);
        BuildToolTab.setLayout(BuildToolTabLayout);
        BuildToolTabLayout.setHorizontalGroup(
            BuildToolTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        BuildToolTabLayout.setVerticalGroup(
            BuildToolTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        ToolBoxPanel.addTab("Build Tools", BuildToolTab);

        jSplitPane1.setRightComponent(ToolBoxPanel);

        WorkBenchWindow.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        WorkBenchWindow.setMinimumSize(new java.awt.Dimension(250, 250));

        WorkbenchPanel.setPreferredSize(new java.awt.Dimension(250, 150));

        javax.swing.GroupLayout WorkbenchPanelLayout = new javax.swing.GroupLayout(WorkbenchPanel);
        WorkbenchPanel.setLayout(WorkbenchPanelLayout);
        WorkbenchPanelLayout.setHorizontalGroup(
            WorkbenchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        WorkbenchPanelLayout.setVerticalGroup(
            WorkbenchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        WorkBenchWindow.setTopComponent(WorkbenchPanel);

        SettingsPanel.setPreferredSize(new java.awt.Dimension(250, 50));

        javax.swing.GroupLayout SettingsPanelLayout = new javax.swing.GroupLayout(SettingsPanel);
        SettingsPanel.setLayout(SettingsPanelLayout);
        SettingsPanelLayout.setHorizontalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SettingsPanelLayout.setVerticalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        WorkBenchWindow.setRightComponent(SettingsPanel);

        jSplitPane1.setLeftComponent(WorkBenchWindow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuildToolTab;
    private javax.swing.JPanel LanguageTab;
    private javax.swing.JPanel OSTab;
    private javax.swing.JPanel SettingsPanel;
    private javax.swing.JTabbedPane ToolBoxPanel;
    private javax.swing.JSplitPane WorkBenchWindow;
    private javax.swing.JPanel WorkbenchPanel;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

}
