/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.is4300.appman;

/**
 *
 * @author quinc
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        DashTab = new javax.swing.JPanel();
        AppTab = new javax.swing.JPanel();
        NewAppButton = new javax.swing.JButton();
        InfraTab = new javax.swing.JPanel();
        SettingTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DashTabLayout = new javax.swing.GroupLayout(DashTab);
        DashTab.setLayout(DashTabLayout);
        DashTabLayout.setHorizontalGroup(
            DashTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        DashTabLayout.setVerticalGroup(
            DashTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dashboard", DashTab);

        NewAppButton.setText("Create New Application!");
        NewAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAppButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AppTabLayout = new javax.swing.GroupLayout(AppTab);
        AppTab.setLayout(AppTabLayout);
        AppTabLayout.setHorizontalGroup(
            AppTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppTabLayout.createSequentialGroup()
                .addComponent(NewAppButton)
                .addGap(0, 252, Short.MAX_VALUE))
        );
        AppTabLayout.setVerticalGroup(
            AppTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppTabLayout.createSequentialGroup()
                .addComponent(NewAppButton)
                .addGap(0, 252, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Applications", AppTab);

        javax.swing.GroupLayout InfraTabLayout = new javax.swing.GroupLayout(InfraTab);
        InfraTab.setLayout(InfraTabLayout);
        InfraTabLayout.setHorizontalGroup(
            InfraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        InfraTabLayout.setVerticalGroup(
            InfraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Insfrastructure", InfraTab);

        javax.swing.GroupLayout SettingTabLayout = new javax.swing.GroupLayout(SettingTab);
        SettingTab.setLayout(SettingTabLayout);
        SettingTabLayout.setHorizontalGroup(
            SettingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        SettingTabLayout.setVerticalGroup(
            SettingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Settings", SettingTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAppButtonActionPerformed
        // TODO add your handling code here:
        new CreateNewForm(ComponentType.APPLICATION).main(null);
    }//GEN-LAST:event_NewAppButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppTab;
    private javax.swing.JPanel DashTab;
    private javax.swing.JPanel InfraTab;
    private javax.swing.JButton NewAppButton;
    private javax.swing.JPanel SettingTab;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
